services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./deployment/scripts:/docker-entrypoint-initdb.d

  wallet-api:
    build:
      context: ./src
      dockerfile: ../deployment/Dockerfile
    container_name: wallet-api
    environment:
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - "5065:80"
    depends_on:
      - db

volumes:
  postgres_data: